### ISSUE TITLE
Add log

### ISSUE THREAD

**Issue by sapozhkov** [sapozhkov/goal#3]
Create log table of goal editions

it must worl like a redmine. just to have an opportunity to write messages and see log of changes
- id
- goal_id
- date [datetime]
- data
- message

Format - json

```
message: 'text'
fields:
    date:
        old: 12-12-20012
        new: 14-12-20012
    title:
        old: 'aslkdf'
        new: 'ksnklgd'
    status: ...
        old: 1
        new: 2
    ...
```

showing will be done an another issue
