### ISSUE TITLE
Log message

### ISSUE THREAD

**Issue by sapozhkov** [sapozhkov/goal#9]
Form - add message field.

View - add list of log values. Order by date.

Data (json)

```
    date:
        old: 12-12-20012
        new: 14-12-20012
    title:
        old: 'aslkdf'
        new: 'ksnklgd'
    status: ...
        old: 1
        new: 2
    ...
```
